fieldLayouts:
  8b23e078-e533-4583-b556-9367ceed0e65:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 185bce59-21d5-42f4-b64b-31fbb4103a72
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3c2ee3b4-e5ad-42a9-8e8e-824eed16c256
        userCondition: null
handle: lineupOverview
hasTitleField: false
name: LineupOverview
section: 21b4bc69-9791-412f-b97a-a2b725c8281d # LineupOverview
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
